name: main CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: ['ubuntu', 'macos']
        python-version: ['3.6', '3.8']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Conda
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge --file ci/conda_requirements.txt 

      - name: Install CI packages
        run: conda install -c conda-forge flake8 coveralls

      - name: Install program
        run: pip install -e .

      - name: Check style
        run: flake8

      - name: Run unit tests
        run: coverage run -m unittest

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
