name: main CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: ['ubuntu']
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Install dependencies
        run: conda install --file ci/conda_requirements.txt 

      - name: Install CI packages
        run: conda install flake8 coveralls

      - name: Install program
        run: pip install -e .

      - name: Check style
        run: flake8

      - name: Run unit tests
        run: coverage run -m unittest

      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@v1.1.2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
